language: node_js
env:
    global:
      - NODE_OPTIONS="--experimental-json-modules"
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
script:
  - yarn tsc -d
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
